### ISSUE TITLE
role discovery data is unavailable 

### ISSUE THREAD

**Issue by krishnazure** [LukeTillman/killrvideo-csharp#3]
I download the new code and encounter the following issues. 
Azure Tools error.
![tools error](https://cloud.githubusercontent.com/assets/5904129/6770275/a6fffcc8-d091-11e4-873b-97b0a889bdb7.jpg)

After updating to the latest tools release , its fails with 
![role discovery data error](https://cloud.githubusercontent.com/assets/5904129/6770269/79370502-d091-11e4-892d-24afc3f86dee.jpg)

Any suggestions to resolve the issues.

**Comment by LukeTillman** [comment]
You need to set the `KillrVideo.Azure` project as the startup project when you build/run so that the site is launched on the emulator locally.  Right-click on the `KillrVideo.Azure` project inside of Visual Studio, then choose the "Set as StartUp Project" option from the menu.  Then when the app starts, you should see it launch the Azure emulator.
